config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, :controllers => {
    :confirmations => 'users/confirmations'
  }
  resources :users, only: %i[index show] do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :categories, only: [:create, :destroy, :index]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.micropost_id = params[:micropost_id]
    if @comment.save
      flash[:success] = 'コメントしました'
      redirect_to @comment.micropost
    else
      @micropost = Micropost.find(params[:micropost_id])
      @comments = @micropost.comments
      render template: 'microposts/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = 'コメントを削除しました'
    redirect_to @comment.micropost
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def correct_user
      @comment = current_user.comments.find_by(id: params[:id])
      redirect_to root_url if @comment.nil?
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
  <img src='<%= comment.user.image %>' class="icon_image" alt="ユーザーアイコン">
  <span class="user"><%= link_to comment.user.username, comment.user %></span>
  <span class="content"><%= comment.content %></span>
  <span class="timestamp">
    <%= time_ago_in_words(comment.created_at) %>前
    <% if current_user?(comment.user) %>
      <%= link_to "削除", micropost_comment_path(comment.micropost, comment), method: :delete,
                                       data: { confirm: "削除しますか？" } %>
    <% end %>
  </span>
</li>