config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, :controllers => {
    :confirmations => 'users/confirmations'
  }
  resources :users, only: %i[index show] do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :categories, only: [:create, :destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { maximum: 10 }
  validates :user_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  counter_culture :micropost
  validates :user_id, presence: true
  validates :micropost_id, presence: true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :iine_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :time, presence: true
  validates :start_time, presence: true
  validates :subject, presence: true

  def iine(user)
    likes.create(user_id: user.id)
  end

  def uniine(user)
    likes.find_by(user_id: user.id).destroy
  end

  def iine?(user)
    iine_users.include?(user)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy,
                                  inverse_of: 'follower'
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy,
                                   inverse_of: 'followed'
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :categories, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :username, presence: true, uniqueness: true, length: { maximum: 30 }
  mount_uploader :image, ImageUploader

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :correct_user, only: [:destroy]

  def index
    @category = Category.new
    @categories = current_user.categories
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      flash[:success] = 'カテゴリを追加しました'
      redirect_to categories_path
    else
      @categories = Category.where(user_id: current_user.id)
      render 'index'
    end
  end

  def destroy
    @category.destroy
    flash[:success] = 'カテゴリを削除しました'
    redirect_to categories_path
  end

  private

    def correct_user
      @category = current_user.categories.find_by(id: params[:id])
      redirect_to categories_path if @category.nil?
    end

    def category_params
      params.require(:category).permit(:name, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.micropost_id = params[:micropost_id]
    if @comment.save
      flash[:success] = 'コメントしました'
      redirect_to @comment.micropost
    else
      @micropost = Micropost.find(params[:micropost_id])
      @comments = @micropost.comments
      render template: 'microposts/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = 'コメントを削除しました'
    redirect_to @comment.micropost
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def correct_user
      @comment = current_user.comments.find_by(id: params[:id])
      redirect_to root_url if @comment.nil?
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @micropost = Micropost.find(params[:micropost_id])
    return if @micropost.iine?(current_user)

    @micropost.iine(current_user)
    @micropost.reload
    respond_to do |format|
      format.html { redirect_to request.referer || root_url }
      format.js
    end
  end

  def destroy
    @micropost = Like.find(params[:id]).micropost
    return unless @micropost.iine?(current_user)

    @micropost.uniine(current_user)
    @micropost.reload
    respond_to do |format|
      format.html { redirect_to request.referer || root_url }
      format.js
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    return unless user_signed_in?

    @micropost  = current_user.microposts.build
    @feed_items = current_user.feed.paginate(page: params[:page], per_page: 5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[following followers]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 5)
  end

  def following
    @title = 'Following'
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page], per_page: 10)
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 10)
    render 'show_follow'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  BASE_TITLE = 'Study App'.freeze
  def full_title(page_title)
    if page_title.blank?
      BASE_TITLE
    else
      "#{page_title} | #{BASE_TITLE}"
    end
  end

  # 渡されたユーザーがカレントユーザーであればtrueを返す
  def current_user?(user)
    user && user == current_user
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <li class="navbar-brand">
      <%= link_to "Study App", root_path %>
    </li>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item nav-link"><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li class="nav-item nav-link">
              <%= link_to "マイページ", current_user %>
          </li>
          <li class="nav-item nav-link">
              <%= link_to "カテゴリー", categories_path %>
          </li>
          <li class="nav-item nav-link">
              <%= link_to "友達を探す", users_path %>
          </li>
          <li class="nav-item nav-link">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li class="nav-item nav-link">
              <%= link_to "ログイン", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>
    <div class="container-fluid py-4 mw-md">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_home_not_user_signed_in.html.erb
<div id="home" class="big-bg">
  <div class="center jumbotron home-content">
      <h1 class="page-title">Study App</h1>
      <h2>
        勉強をもっと楽しく、続けませんか？<br>
        時間を記録し成長を感じましょう
      </h2>
      <%= link_to "新規登録", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/pages/_home_user_signed_in.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <%= render 'pages/home_user_signed_in' %>
<% else %>
  <%= render 'pages/home_not_user_signed_in' %>
<% end %>

app/views/shared/_calendar.html.erb
<%= month_calendar events: user.microposts do |date, microposts| %>
  <%= "#{date.day}日" %>
  <div>
    <%= "#{microposts.pluck(:time).sum}時間" unless microposts.pluck(:time).sum == 0 %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= object.errors.count %>個のエラーがあります
    </div>
    <ul >
      <% object.errors.full_messages.each do |msg| %>
        <li ><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items,
                    params: { controller: :pages, action: :home } %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true, id: :micropost_form) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.number_field :time, step: "0.5", min: '0', max: '10', class: 'form-time', placeholder: "勉強時間を入力してください（h）" %>
  </div>
  <div class="form-group">
    <%= f.collection_select :subject, current_user.categories, :name, :name, { prompt: 'カテゴリを選択してください' }, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.text_area :content, placeholder: "メモを記入してください" %>
  </div>
  <div class="form-group">
    <%= f.date_field :start_time %>
  </div>
  <%= f.submit "投稿", class: "btn btn-primary btn-submit" %>
<% end %>
<hr class="border-dark my-5">
<div class="form-group">
  <%= link_to "実施したカテゴリーがありませんか？", categories_path, class: 'btn btn-secondary btn-block' %><br />
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="study-time">
  <p><%= "勉強総計：#{@user.microposts.pluck(:time).sum}　時間" %></p>
</div>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1>
  <img src=<%= current_user.image %> class = "icon_image">
  <%= current_user.username %>
</h1>
<% if @user == current_user %>
  <%= link_to "プロフィール編集", edit_user_registration_path %>
<% end %>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <h5>
      <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    </h5>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>